const express = require('express')
const bodyParser = require('body-parser')
const userRouter = require('./user/router')
const playlistRouter = require('./playlist/router')
const songRouter = require('./song/router')
const loginRouter = require('./auth/router')
const JWT = require('./auth/jwt')
const user = require('./user/model')
const playlist = require('./playlist/model')
const song = require ('./song/model')
const db = require('./db.js')
const app = express()
const jsonParser = bodyParser.json()
app.use(jsonParser)
app.use(userRouter)
app.use(playlistRouter)
app.use(songRouter)
app.use(loginRouter)
const port = process.env.PORT || 4000
app.listen(port, () => `Listening on port ${port}`)